name: Dashboard

channels: 
  - defaults
  - conda-forge
  - bioconda 


dependencies:
  - python=3.6.7
  - pandas
  - matplotlib
  - seaborn
  - dash
  - dash-core-components
  - dash-html-components
  - dash-table
  - dash-daq
  - bcftools>=1.9
  - snpeff=4.5covid19
  - snpsift=4.3.1t
