name: Dashboard

channels: 
  - defaults
  - conda-forge



dependencies:
  - python=3.6.7
  - pandas
  - matplotlib
  - seaborn
  - dash
  - dash-core-components
  - dash-html-components
  - dash-table
  - dash-daq
